<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>storagemonitor</AssemblyName>
    <RootNamespace>Calloatti.StorageMonitor</RootNamespace>
    <TimberbornPath>C:\Program Files (x86)\Steam\steamapps\common\timberborn_public\Timberborn_Data\Managed</TimberbornPath>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />

  <ItemGroup>
    <DoNotPublicize Include="Timberborn.CoreUI:Timberborn.CoreUI.RadioToggle.RadioButtonSelected" />
    <DoNotPublicize Include="Timberborn.BlueprintSystem:Timberborn.BlueprintSystem.ComponentSpec.EqualityContract" />
    <DoNotPublicize Include="Timberborn.BlueprintSystem:Timberborn.BlueprintSystem.ComponentSpec.PrintMembers" />
  </ItemGroup>

</Project>